language: python
dist: focal
sudo: true
matrix:
  include:
    - python: pypy3.6-7.3.1
      arch: amd64
      env: TOXENV=pypy3 PYTEST_ADDOPTS="--benchmark-skip"
    - python: 3.8
      arch: arm64
      env: TOXENV=py38 PYTEST_ADDOPTS="--benchmark-skip"

install:
  - sudo apt install p7zip-full libarchive-dev
  - pip install tox-travis

script: tox
