name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - name: Fetch release tag
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Set up Python 3.9🐍
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependency
        run: python -m pip install -U pip wheel setuptools setuptools_scm[toml] twine
      - name: Build release assets
        run: |
          python setup.py sdist
          python -m pip wheel .
      - name: twine check
        run: python -m twine check dist/*
      - name: Publish distribution 📦 to Test PyPI
        if: startsWith(github.event.ref, 'refs/heads/master')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.testpypi_password }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
